name: OTF Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Functional Test
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [firefox, chrome, edge]  # Daftar browser yang akan diuji
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Create isolated network
        run: docker network create --driver bridge isolated

      - name: Deploy AUT
        run: docker build -t my-php-site:latest .

      - name: Run AUT
        run: docker run --network=isolated -p 80:80 --name docker-apache -t -d my-php-site:latest

      - name: Get AUT URL
        run: |
          URL=http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1)
          echo "URL=$URL" >> $GITHUB_ENV

      - name: Check AUT Url
        run: curl ${{ env.URL }}

      - name: Selenium Preparation (${{ matrix.browser }})
        run: |
          if [ "${{ matrix.browser }}" == "firefox" ]; then
            docker run --network=isolated -d -p 4444:4444 -p 7900:7900 -v /dev/shm:/dev/shm --name selenium-firefox selenium/standalone-firefox:latest
          elif [ "${{ matrix.browser }}" == "chrome" ]; then
            docker run --network=isolated -d -p 4445:4444 -p 7901:7900 -v /dev/shm:/dev/shm --name selenium-chrome selenium/standalone-chrome:latest
          elif [ "${{ matrix.browser }}" == "edge" ]; then
            docker run --network=isolated -d -p 4446:4444 -p 7902:7900 -v /dev/shm:/dev/shm --name selenium-edge selenium/standalone-edge:latest
          fi

      - name: Wait for Selenium Hub
        run: |
          if [ "${{ matrix.browser }}" == "firefox" ]; then
            while ! curl -s http://localhost:4444/wd/hub/status | grep -q "ready"; do sleep 1; done
          elif [ "${{ matrix.browser }}" == "chrome" ]; then
            while ! curl -s http://localhost:4445/wd/hub/status | grep -q "ready"; do sleep 1; done
          elif [ "${{ matrix.browser }}" == "edge" ]; then
            while ! curl -s http://localhost:4446/wd/hub/status | grep -q "ready"; do sleep 1; done
          fi

      - name: Check the Hub
        run: |
          if [ "${{ matrix.browser }}" == "firefox" ]; then
            curl http://localhost:4444/wd/hub/status
          elif [ "${{ matrix.browser }}" == "chrome" ]; then
            curl http://localhost:4445/wd/hub/status
          elif [ "${{ matrix.browser }}" == "edge" ]; then
            curl http://localhost:4446/wd/hub/status
          fi

      - name: Install Selenium client
        run: pip install -U selenium

      - name: Run tests
        run: python tests/hello_aut.py ${{ env.URL }} ${{ matrix.browser }}

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: Screenshots-${{ matrix.browser }}
          path: screenshot_${{ matrix.browser }}.png

      - name: Stop Docker containers
        run: |
          docker stop docker-apache
          if [ "${{ matrix.browser }}" == "firefox" ]; then
            docker stop selenium-firefox
          elif [ "${{ matrix.browser }}" == "chrome" ]; then
            docker stop selenium-chrome
          elif [ "${{ matrix.browser }}" == "edge" ]; then
            docker stop selenium-edge
          fi